# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/social_db
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis
spring.redis.host=localhost
spring.redis.port=6379

# Server
server.port=8081 
